PINECONE_API_KEY = "pcsk_28Q4q2_SDw7i2iFQPMhCwLg2epj4MoHR3TLqhSfqXEwBGW5pZjo8oLcaSomRKKgKeHk2FD"
AWS_ACCESS_KEY_ID = "ASIAXYKJSOTRGVWNUDJO"
AWS_SECRET_ACCESS_KEY = "Fr2YWXNdXo0l0JlZb5dNZnYOHRU7kgoi+uTDXllq"
AWS_DEFAULT_REGION = "us-east-1"
